site_name: Instalación de Servidores y Clientes
theme:
  name: 'material'
  palette:
    - scheme: default
      primary: grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Introducción: index.md
    - Responsabilidad individual:
        - 'Alumno 1: Adrián': 'ri/alumno1.md'
        - 'Alumno 2: José Juan': 'ri/alumno2.md'
        - 'Alumno 3: Arantxa': 'ri/alumno3.md'
        - 'Alumno 4: Antonio': 'ri/alumno4.md'
    - Responsabilidad grupal:
        - 'SQL Developer': 'rg/sql-developer.md'
        - 'Herramienta web PostgreSQL': 'rg/herramienta-postgresql.md'
        - 'phpMyAdmin': 'rg/phpmyadmin.md'
        - 'Herramienta web MongoDB': 'rg/herramienta-mongodb.md'
        - 'Oracle Enterprise Manager': 'rg/oracle-enterprise-manager.md'
