site_name: Plan de Seguridad para Comvive 
theme:
  name: 'material'
  palette: 
    - scheme: default
      primary: pink
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: pink
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Home: index.md
    - Plan de seguridad:
        - 'Inventario de Hardware': 'inventario-hardware.md'
    - Plan de contingencias: about.md
