site_name: Plan de Seguridad para Comviviendo
theme:
  name: 'material'
  palette:
    - scheme: default
      primary: grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Introducción: index.md
    - Plan de seguridad:
        - '1. Análisis de la empresa': 'analisis-empresa.md'
        - '2. Inventario de Hardware': 'inventario-hardware.md'
        - '3. Inventario de Software': 'inventario-software.md'
        - '4. Inventario de Comunicaciones': 'inventario-comunicaciones.md'
        - '5. Datos': 'datos-proteger.md'
        - '6. Análisis de riesgos': 'analisis-riesgos.md'
        - '7. Análisis de vulnerabilidades': 'analisis-vulnerabilidades.md'
        - 'Protección contra amenazas': 'proteccion-amenazas.md'
    - Plan de contingencias: plan-contingencias.md
    - Controles periódicos: controles-periodicos.md
    - Bibliografía: bibliografia.md
