site_name: Grupales de BD Grupo C 22/23
theme:
  name: 'material'
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
  icon:
    logo: material/database
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Cambiar a tema oscuro
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Cambiar a tema normal
nav:
    - Principal: index.md
    - Práctica 1 servidores y clientes:
        - 'Introducción': 'p1-servidores-clientes/intro.md'
        - Responsabilidad individual:
            - 'Alumno 1: Adrián': 'p1-servidores-clientes/ri/alumno1.md'
            - 'Alumno 2: José Juan': 'p1-servidores-clientes/ri/alumno2.md'
            - 'Alumno 3: Arantxa': 'p1-servidores-clientes/ri/alumno3.md'
            - 'Alumno 4: Antonio': 'p1-servidores-clientes/ri/alumno4.md'
        - Responsabilidad grupal:
            - 'SQL Developer': 'p1-servidores-clientes/rg/sql-developer.md'
            - 'Herramienta web PostgreSQL': 'p1-servidores-clientes/rg/herramienta-postgresql.md'
            - 'phpMyAdmin': 'p1-servidores-clientes/rg/phpmyadmin.md'
            - 'Herramienta web MongoDB': 'p1-servidores-clientes/rg/herramienta-mongodb.md'
            - 'Oracle Enterprise Manager': 'p1-servidores-clientes/rg/oracle-enterprise-manager.md'
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
plugins:
  - glightbox
  - search
  - mkdocs-asciinema
repo_url: https://github.com/adriasir123/p1-bd-servidores-clientes
repo_name: p1-bd-servidores-clientes