site_name: Plan de Seguridad para Comviviendo
theme:
  name: 'material'
  palette:
    - scheme: default
      primary: grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Introducción: index.md
    - Plan de seguridad:
        - 'Análisis de la empresa': 'analisis-empresa.md'
        - Activos:
            - 'Inventario de Hardware': 'inventario-hardware.md'
            - 'Inventario de Software': 'inventario-software.md'
            - 'Inventario de Comunicaciones': 'inventario-comunicaciones.md'
            - 'Datos': 'datos-proteger.md'
        - 'Identificación de amenazas': 'identificacion-amenazas.md'
        - 'Valoración de amenazas': 'valoracion-amenazas.md'
        - 'Protección contra amenazas': 'proteccion-amenazas.md'
    - Plan de contingencias: plan-contingencias.md
    - Controles periódicos: controles-periodicos.md
